Nihat/Nihat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sorgu/',include('sorgu.urls')),

]

Nihat/sorgu/urls.py
from django.urls import path

from . import views                                                      # views modelin tanitmi

app_name = 'sorgu'                                                       # urllerin name vasitesi ile tespiti

urlpatterns = [

    # ex: /sorgu/
    path('', views.esas, name='esas'),                                   # esas sehife urlsi

    # ex: /sorgu/5/
    path('<int:niko_id>/', views.etrafli, name='etrafli'),              # etrafli sehifesi urlsi

    # ex: /sorgu/5/netice/
    path('<int:niko_id>/netice/', views.netice, name='netice'),         # netice sehifesi urlsi

    # ex: /sorgu/5/vote/
    path('<int:niko_id>/vote/', views.vote, name='vote'),               # sesverme sehifesi urlsi
]

Nihat/sorgu/models.py
from django.db import models
import datetime                                                                   # sual modelmizin icine elave olunan 'bu yaxin' funksiyasi ucun :)
from django.utils import timezone                                                 # zona vaxti ucun
class Sual(models.Model):                                                         # sual modelim
    sual_text = models.CharField(max_length=200)                                  # daxil etdiyim sual_text
    cap_tarixi = models.DateTimeField('cap olundu :')                             # cap tarixiqeyd etmek ucun
    def __str__(self):                                                            # yaradilan sualin  ustunde qeyd olunmasi
        return self.sual_text

    def bu_yaxin(self):
        return self.cap_tarixi >= timezone.now() - datetime.timedelta(days=1)

class Cavab(models.Model):                                                        # cavab modelim
    sual = models.ForeignKey(Sual, on_delete=models.CASCADE)                      # verilen suala kecid modeli
    cavab_text = models.CharField(max_length=200)                                 # daxil etdiyim cavab_text
    votes = models.IntegerField(default=0)                                        # ses modeli
    def __str__(self):                                                            # yaradilan cavabin ustunde , yazilan yavabin eks olunmasi
        return self.cavab_text

Nihat/sorgu/views.py
from django.shortcuts import render,get_object_or_404,redirect              # elave edilmeyen sual ve ya cavab olduqda 404 susmaya qarsi

from django.http import HttpResponseRedirect                                # elaqe funksiyasi dasiyir

from django.urls import reverse                                              # urlde yaratdigimiz name sablon adlarindan istifade ucun

from .models import Sual,Cavab                                               # modelde yaratdigimiz sual,cavab modellerinin tanitimi


def esas(request):                                                           # esas sehife funksiyam
    sual_list = Sual.objects.order_by('-cap_tarixi')[:5]                     # qeyd olunan en son 5 sual

    context = {'sual_list': sual_list}

    return render(request, 'sorgu/esas.html', context)                       # html file ile etrafli(detail) sehifeye kecidin yaradilmasi


def etrafli(request, niko_id):                                               # etrafli yeni cavablarin oldugu sehife
    sual = get_object_or_404(Sual, pk=niko_id)

    return render(request, 'sorgu/etrafli.html', {'sual': sual})


def netice(request, niko_id):                                                # sesvermeden sonra acilan sehife
    sual = get_object_or_404(Sual, pk=niko_id)

    return render(request, 'sorgu/netice.html', {'sual': sual})


def vote(request, niko_id):                                                  # vote(sesverme) sehifesi
    sual = get_object_or_404(Sual, pk=niko_id)

    try:

        selected_choice = sual.cavab_set.get(pk=request.POST['cavab57'])

    except (KeyError, Cavab.DoesNotExist):

        return render(request, 'sorgu/etrafli.html', {                       # sesvermenin netice sehifesine yansimasi ucun kecid
            'sual': sual,
            'error_message': " Cavab secin.",
        })

    else:
        selected_choice.votes += 1

        selected_choice.save()

        return HttpResponseRedirect(reverse('sorgu:netice', args=(sual.id,)))







Nihat/sorgu/templates/sorgu/esas.html
{% if sual_list %}
    <ul>
    {% for sual in sual_list %}
        <li><a href="/sorgu/{{ sual.id }}/">{{ sual.sual_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Hec bir sorgu yoxdur !</p>
{% endif %}

{% load static %}
<link rel="stylesheet" href="{% static 'sorgu/style.css' %}">

Nihat/sorgu/templates/sorgu/etrafli.html
<form action="{% url 'sorgu:vote' sual.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ sual.sual_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% for cavab57 in sual.cavab_set.all %}
        <input type="radio" name="cavab57" id="cavab57{{ forloop.counter }}" value="{{ cavab57.id }}">
        <label for="cavab57{{ forloop.counter }}">{{ cavab57.cavab_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

Nihat/sorgu/templates/sorgu/netice.html
<h1>{{ sual.sual_text }}</h1>

<ul>
{% for cavab57 in sual.cavab_set.all %}
    <li>{{ cavab57.cavab_text }} -- {{ cavab57.votes }} vote{{ cavab57.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'sorgu:etrafli' sual.id %}">Vote again?</a>